### ISSUE TITLE
Virtual Private Cloud quota limit is not clearly stated

### ISSUE THREAD

**Issue by mperkinson** [IBM-Bluemix-Docs/vpc-on-classic#2]
From the Virtual Private Cloud Quota page, [https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-quotas](https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-quotas) , the limit of 5 VPCs per account does not accurately reflect the true quota. The way in which the quota is presented leads one to believe that a single account can only have 5 VPCs provisioned. See graphic below.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/36716743/58725665-b58cdf80-83ad-11e9-8d16-fe035eb826d7.png">

The true quota is 5 VPCs per region in a single account. For example, today there are three MZRs that have VPC available. In a single account, I can provision 5 VPCs from each MZR. This means that I can have maximum of 15 VPCs in my account (5 VPCs * 3 MZRs = 15 VPCs).

The quota information on the page needs to be updated to more clearly state the quota.

**Comment by ibm-cos-help** [comment]
You are right, fixing this soon.

**Comment by ayta5** [comment]
Can you also please look at the ACL quotas. It says 30 per account, but 200 per region. That looks incorrect as well because if 200 ACLs are allowed in a region, that crosses the 30 already in the account. @ibm-cos-help

**Comment by mperkinson** [comment]
I agree that this does not look correct, but I do not know what the accurate language would be. I would suggest speaking to someone in Offering Management.

**Comment by ibm-cos-help** [comment]
The quota is 30. Fix coming!

**Comment by ibm-cos-help** [comment]
Fixed: https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-quotas
