### ISSUE TITLE
Lack of clarity in pricing for VPNaaS

### ISSUE THREAD

**Issue by jonnywillmac** [IBM-Bluemix-Docs/vpc-on-classic#3]
Could we get clarity on VPN deployment costs please.

**Comment by ibm-cos-help** [comment]
LB and VPN are GA now, pricing has been updated:

https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-pricing-for-vpc#lb-for-vpc-pricing

https://cloud.ibm.com/docs/vpc-on-classic?topic=vpc-on-classic-pricing-for-vpc#vpn-for-vpc-pricing
